# Generated by Django 4.0.6 on 2022-11-20 17:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduling_date_start', models.DateField(default='2020-02-22')),
                ('scheduling_date_end', models.DateField()),
                ('scheduling_time_start', models.TimeField(choices=[('07:00:00', '7H00'), ('07:50:00', '7H50'), ('08:40:00', '8H40'), ('09:30:00', '9H30'), ('09:50:00', '9H50'), ('10:40:00', '10H40'), ('11:30:00', '11H30'), ('12:20:00', '12H20'), ('13:20:00', '12H20'), ('14:10:00', '14H10'), ('15:00:00', '15H00'), ('15:50:00', '15H50'), ('16:10:00', '16H10'), ('17:00:00', '17H00'), ('17:50:00', '17H50'), ('18:40:00', '18H40'), ('18:10:00', '18H10'), ('19:00:00', '19H00'), ('19:50:00', '19H50'), ('20:40:00', '20H40'), ('20:50:00', '20H50'), ('21:40:00', '21H40'), ('22:30:00', '22H30')], default='07:00:00')),
                ('scheduling_time_end', models.TimeField(choices=[('07:00:00', '7H00'), ('07:50:00', '7H50'), ('08:40:00', '8H40'), ('09:30:00', '9H30'), ('09:50:00', '9H50'), ('10:40:00', '10H40'), ('11:30:00', '11H30'), ('12:20:00', '12H20'), ('13:20:00', '12H20'), ('14:10:00', '14H10'), ('15:00:00', '15H00'), ('15:50:00', '15H50'), ('16:10:00', '16H10'), ('17:00:00', '17H00'), ('17:50:00', '17H50'), ('18:40:00', '18H40'), ('18:10:00', '18H10'), ('19:00:00', '19H00'), ('19:50:00', '19H50'), ('20:40:00', '20H40'), ('20:50:00', '20H50'), ('21:40:00', '21H40'), ('22:30:00', '22H30')], default='07:50:00')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.room')),
            ],
        ),
    ]
