# Generated by Django 4.0.6 on 2022-07-23 14:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0003_alter_room_room_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduling_date_start', models.DateField(default='2020-02-22')),
                ('scheduling_date_end', models.DateField()),
                ('scheduling_time_start', models.TimeField()),
                ('scheduling_time_end', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(default='', max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
