# Generated by Django 4.0.6 on 2022-07-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0003_alter_scheduling_scheduling_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='scheduling',
            name='scheduling_start',
            field=models.TimeField(),
        ),
    ]
