# Generated by Django 4.0.6 on 2022-07-18 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='img',
            field=models.URLField(null=True),
        ),
    ]
