# Generated by Django 4.0.6 on 2022-11-20 17:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(choices=[('Laboratório', 'Laboratorio'), ('Sala de Aula', 'Salaaula')], default='Sala de Aula', max_length=50)),
                ('block', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
