# Generated by Django 4.0.6 on 2022-07-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_rename_type_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('Laboratório', 'Laboratorio'), ('Sala de Aula', 'Salaaula')], default='Sala de Aula', max_length=50),
        ),
    ]
